spring.application.name=flink-boot
spring.main.web-application-type=none
logging.level.org.apache.flink=WARN
spring.devtools.restart.enabled=false
fraud.job.bootstrap-servers=localhost:9092
fraud.job.transactions-topic=transactions
fraud.job.alerts-topic=fraud-alerts
fraud.job.group-id=fraud-detector
fraud.job.large-transaction-threshold=50000
fraud.job.rapid-total-threshold=70000
